RowanSpeech_Text_HelloThere::
    .string "Hello there!\n"
    .string "It's so very nice to meet you!\p"
    .string "Welcome to the world of Pokémon!$"

RowanSpeech_Text_MyNameIsRowan::
    .string "My name is Rowan\p"
    .string "However, everyone just calls me\n"
    .string "the Pokémon Professor.\p"
    .string "Before I go any further, is this\n"
    .string "your first adventure?\p"
    .string "If you need advice, I'm certainly\n"
    .string "capable of giving it.$"

RowanSpeech_Text_AnythingElse::
    .string "Would you like to know more about\n"
    .string "anything else?$"

@CONTROL INFO NEEDED-ADVENTURE INFO NEEDED-NO INFO NEEDED

RowanSpeech_Text_ThisWorldIsInhabitedByPokemon::
    .string "This world is widely inhabited by\n"
    .string "creatures known as Pokémon.$"

RowanSpeech_Text_IHaveAPokeball::
    .string "Here, I have a Pokéball.\p"
    .string "Touch the button in the middle of\n"
    .string "the Pokéball, if you'd please.$"

RowanSpeech_Text_WeLiveAlongsidePokemon::
    .string "We humans live alongside Pokémon\n"
    .string "as friends.\p"
    .string "At times we play together,\n"
    .string "and at other times we\l"
    .string "work together.\p"
    .string "Some people use their Pokémon\p"
    .string "to battle and develop\l"
    .string "closer bonds with them.\p"
    .string "What do i do?\p"
    .string "I conduct research so that we may\n"
    .string "learn more about Pokémon.$"

RowanSpeech_Text_TellMeMoreAboutYourself::
    .string "Now, why don't you tell me\n"
    .string "a little bit about yourself?$"

@slide in dawn and lucas sprites

RowanSpeech_Text_AreYouABoyOrGirl::
    .string "Are you a boy?\n"
    .string "Or are you a girl?$"

@slide out other gender

RowanSpeech_Text_YoureABoy::
    .string "All right, so you're a boy?$"

RowanSpeech_Text_YoureAGirl::
    .string "All right, so you're a girl?$"

RowanSpeech_Text_WhatIsYourName::
    .string "Tell me, what is your name?$"

@slide out player sprite
@name player character

RowanSpeech_Text_YourNameIs::
    .string "Your name is {PLAYER}?$"

RowanSpeech_Text_OkSoYoure::
    .string "Ok...\n"
    .string "So, you're {PLAYER}?\p"
    .string "A fine name that is!$"

@slide in barry sprite

RowanSpeech_Text_ThisBoyHere::
    .string "Now, this boy here...\n"
    .string "I belive he's your friend.$"

RowanSpeech_Text_WhatMightHisNameBe::
    .string "What might his name be?$"

@name rival 
@remove barry sprite

RowanSpeech_RivalIsIt::
    .string "{RIVAL}, is i?\n"
    .string "That's your friend's name?$"

@slide in rowan sprite

RowanSpeech_Text_TheTimeHasCome::
    .string "All right, {PLAYER}, the time\n"
    .string "has come.\p"
    .string "Your very own tale of grand\n"
    .string "adventure is about to unfold.\p"
    .string "On your journey, you will meet\n"
    .string "countless people and Pokémon\p"
    .string "I'm sure that along the way you will\n"
    .string "discover many things, perhaps even\l"
    .string "something about yourself.\p"
    .string "Now, go on, leap into the world of Pokémon!$"

@shrink player character to chibi 

@Intro TV Text
RowanTV_Text_PokemonByOurSide::
    .string "'Pokémon are by our side, always.\n"
    .string "I hope you will understand the meaning\n"
    .string "of those words.'\n\n"
    .string "That was the comment left by Prof. Rowan,\n"
    .string "who has returned to Sinnoh from the\n"
    .string "Kanto region.$"
