Route206_MapScripts::
	.byte 0


Route207_EventScript_Theodore::
	trainerbattle_single TRAINER_THEODORE, Route207_Text_TheodoreIntro, Route207_Text_TheodoreDefeated
	msgbox Route207_Text_TheodorePostBattle, MSGBOX_AUTOCLOSE
	end

Route207_EventScript_Axel::
	trainerbattle_single TRAINER_AXEL, Route207_Text_AxelIntro, Route207_Text_AxelDefeated
	msgbox Route207_Text_AxelPostBattle, MSGBOX_AUTOCLOSE
	end

Route207_EventScript_Megan::
	trainerbattle_single TRAINER_MEGAN, Route207_Text_MeganIntro, Route207_Text_MeganDefeated
	msgbox Route207_Text_MeganPostBattle, MSGBOX_AUTOCLOSE
	end

Route207_EventScript_James::
	trainerbattle_single TRAINER_JAMES, Route207_Text_JamesIntro, Route207_Text_JamesDefeated
	msgbox Route207_Text_JamesPostBattle, MSGBOX_AUTOCLOSE
	end

Route207_EventScript_Nicole::
	trainerbattle_single TRAINER_NICOLE, Route207_Text_NicoleIntro, Route207_Text_NicoleDefeated
	msgbox Route207_Text_NicolePostBattle, MSGBOX_AUTOCLOSE
	end

Route207_EventScript_John::
	trainerbattle_single TRAINER_JOHN, Route207_Text_JohnIntro, Route207_Text_JohnDefeated
	msgbox Route207_Text_JohnPostBattle, MSGBOX_AUTOCLOSE
	end

Route207_EventScript_Kayla::
	trainerbattle_single TRAINER_KAYLA, Route207_Text_KaylaIntro, Route207_Text_KaylaDefeated
	msgbox Route207_Text_KaylaPostBattle, MSGBOX_AUTOCLOSE
	end

Route207_EventScript_Ryan::
	trainerbattle_single TRAINER_RYAN, Route207_Text_RyanIntro, Route207_Text_RyanDefeated
	msgbox Route207_Text_RyanPostBattle, MSGBOX_AUTOCLOSE
	end

Route207_EventScript_Rachel::
	trainerbattle_single TRAINER_RACHEL, Route207_Text_RachelIntro, Route207_Text_RachelDefeated
	msgbox Route207_Text_RachelPostBattle, MSGBOX_AUTOCLOSE
	end

Route207_Text_TheodoreIntro:
	.string "Let's Battle!$"
Route207_Text_TheodoreDefeated:
	.string "I lost!$"
Route207_Text_TheodorePostBattle::
	.string "Bye, see you later!$"

Route207_Text_AxelIntro:
	.string "Let's Battle!$"
Route207_Text_AxelDefeated:
	.string "I lost!$"
Route207_Text_AxelPostBattle::
	.string "Bye, see you later!$"

Route207_Text_MeganIntro:
	.string "Let's Battle!$"
Route207_Text_MeganDefeated:
	.string "I lost!$"
Route207_Text_MeganPostBattle::
	.string "Bye, see you later!$"

Route207_Text_JamesIntro:
	.string "Let's Battle!$"
Route207_Text_JamesDefeated:
	.string "I lost!$"
Route207_Text_JamesPostBattle::
	.string "Bye, see you later!$"

Route207_Text_NicoleIntro:
	.string "Let's Battle!$"
Route207_Text_NicoleDefeated:
	.string "I lost!$"
Route207_Text_NicolePostBattle::
	.string "Bye, see you later!$"

Route207_Text_JohnIntro:
	.string "Let's Battle!$"
Route207_Text_JohnDefeated:
	.string "I lost!$"
Route207_Text_JohnPostBattle::
	.string "Bye, see you later!$"

Route207_Text_KaylaIntro:
	.string "Let's Battle!$"
Route207_Text_KaylaDefeated:
	.string "I lost!$"
Route207_Text_KaylaPostBattle::
	.string "Bye, see you later!$"

Route207_Text_RyanIntro:
	.string "Let's Battle!$"
Route207_Text_RyanDefeated:
	.string "I lost!$"
Route207_Text_RyanPostBattle::
	.string "Bye, see you later!$"

Route207_Text_RachelIntro:
	.string "Let's Battle!$"
Route207_Text_RachelDefeated:
	.string "I lost!$"
Route207_Text_RachelPostBattle::
	.string "Bye, see you later!$"
